add_newline = true

format = """
$directory $git_branch$git_status\
$fill\
$python\
$lua\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$docker_context\
$cmd_duration
$character
"""

command_timeout = 200

[fill]
symbol = " "

[character]                    
success_symbol = "[â•°â”€ î©± ï‹](bold fg:cyan)"
error_symbol = "[â•°â”€ ï€ ï‹](bold fg:red)"

[git_branch]
style = "italic cyan"
symbol = "ó°˜¬"
format = "[$symbol $branch(:$remote_branch)]($style)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = " î®«"
up_to_date = " ï€Œ"
untracked  = " ?"
modified   = " î©±"
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[directory]
#home_symbol = " ï‘­ "
read_only = " ï‘– "
style = "fg:green"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = " â€¢â€¢/"
format = '[â•­â”€ $path]($style)'

[cmd_duration]
# min_time = 0
format = '[ó°ª¢ $duration](bold fg:green)'

[c]
symbol = "î˜ "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:green fg:black"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = "î‰µ "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:green fg:black"
format = '[(\($virtualenv\))]($style) î©± '

[rust]
symbol = "î¨"
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'